t_exception_propagation-x_declaration_parameter.adb:39:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:40:7: Error: declaration: declaration can propagate exceptions (declaration at level 1)
t_exception_propagation-x_declaration_parameter.adb:50:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:51:7: Error: declaration: declaration can propagate exceptions (declaration at level 2)
t_exception_propagation-x_declaration_parameter.adb:61:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Gen_Param: subprogram "Proc10" can propagate exceptions, used as call-back in instantiation at t_exception_propagation-x_declaration_parameter.adb:128:4
t_exception_propagation-x_declaration_parameter.adb:96:4: Error: Gen_Param: generic "Gen1" can propagate exceptions, instance "Inst1" at t_exception_propagation-x_declaration_parameter.adb:100:4 used as call-back in instantiation at t_exception_propagation-x_declaration_parameter.adb:129:4
t_exception_propagation-x_declaration_parameter.adb:131:4: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param10: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:135:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param11: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:141:4
t_exception_propagation-x_declaration_parameter.adb:34:4: Error: Param11: subprogram "Proc11" can propagate exceptions (declaration at level 1), used as call-back at t_exception_propagation-x_declaration_parameter.adb:142:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param12: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:147:4
t_exception_propagation-x_declaration_parameter.adb:34:4: Error: Param12: subprogram "Proc11" can propagate exceptions (declaration at level 1), used as call-back at t_exception_propagation-x_declaration_parameter.adb:148:4
t_exception_propagation-x_declaration_parameter.adb:49:4: Error: Param12: subprogram "Proc12" can propagate exceptions (declaration at level 2), used as call-back at t_exception_propagation-x_declaration_parameter.adb:149:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param13: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:153:4
t_exception_propagation-x_declaration_parameter.adb:34:4: Error: Param13: subprogram "Proc11" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:154:4
t_exception_propagation-x_declaration_parameter.adb:49:4: Error: Param13: subprogram "Proc12" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:155:4
t_exception_propagation-x_declaration_parameter.adb:60:4: Error: Param13: subprogram "Proc13" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:156:4
t_exception_propagation-x_declaration_parameter.adb:69:4: Error: Param10: subprogram "Proc2" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:158:4
t_exception_propagation-x_declaration_parameter.adb:77:4: Error: Param10: subprogram "Proc3" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:159:4
t_exception_propagation-x_declaration_parameter.adb:96:4: Error: Param10: generic "Gen1" can propagate exceptions, instance "Inst1" at t_exception_propagation-x_declaration_parameter.adb:100:4 used as call-back at t_exception_propagation-x_declaration_parameter.adb:160:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param4: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:162:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param4: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:163:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param2: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:165:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param3: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:167:4
t_exception_propagation-x_interface.adb:7:4: Error: interf: subprogram "Proc_C1" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:11:4: Error: interf: subprogram "Proc_C2" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:21:4: Error: interf: subprogram "Proc_C3" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:33:4: Error: interf: subprogram "F" can propagate exceptions, interfaced to C
t_exception_propagation-x_task.adb:4:4: Error: task: task "T1" can propagate exceptions
t_exception_propagation-x_task.adb:19:4: Error: task: task "T3" can propagate exceptions
t_exception_propagation-x_local_exception.adb:4:4: Found: local: No handler for local exception in enclosing body
t_exception_propagation-x_local_exception.adb:11:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:7:7
t_exception_propagation-x_local_exception.adb:16:7: Found: local: No handler for local exception in enclosing body
t_exception_propagation-x_local_exception.adb:23:7: Found: local: No handler for local exception in enclosing block
t_exception_propagation-x_local_exception.adb:36:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:32:7
t_exception_propagation-x_local_exception.adb:38:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:32:7
t_exception_propagation-x_local_exception.adb:50:7: Found: local: handler can propagate local exception at t_exception_propagation-x_local_exception.adb:45:7
